version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: workplace-roleplay-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - workplace-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  redis-test:
    image: redis:7-alpine
    container_name: workplace-roleplay-redis-test
    ports:
      - "6380:6379"
    command: redis-server --appendonly no --maxmemory 64mb
    networks:
      - workplace-net
    profiles:
      - test

  postgres:
    image: postgres:15-alpine
    container_name: workplace-roleplay-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: workplace_roleplay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - workplace-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  postgres-test:
    image: postgres:15-alpine
    container_name: workplace-roleplay-postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: workplace_roleplay_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_test_password
    networks:
      - workplace-net
    profiles:
      - test

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local

networks:
  workplace-net:
    driver: bridge
